const data=[
    {
        id:'1',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/61amb0CfMGL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"OnePlus 11 5G",
        details:'OnePlus 11 5G (Eternal Green, 8GB RAM, 128GB Storage)',
        rating:'★ ★ ★ ★ ★',
        price:'₹56,998',
        PriceDrop:'-20%',
        GetitBy:'Tommorrow,29 October',
    }
    , {
        id:'2',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/81ZSn2rk9WL._AC_UY327_FMwebp_QL65_.jpg',
        details:'Samsung Galaxy M14 5G (Eternal Green, 8GB RAM, 128GB',
        rating:' ★ ★ ★ ★ ★',
        price:'₹11,990',
        PriceDrop:'-40%',
        GetitBy:'Monday,8october',
    }
    , {
        id:'3',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/61SmnheBBRL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Redmi 12 5G",
        details:'Redmi 12 5G Moonstone Silver ',
        rating:'★ ★ ★ ★ ★',
        price:'₹11,999',
        PriceDrop:'-25%',
        GetitBy:'Tommorrow,29October',
    }
    , {
        id:'4',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/81xJ80yRRzL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Samsung Galaxy M04",
        details:'Samsung Galaxy M04 Dark Blue,',
        rating:'★ ★ ★ ★ ★',
        price:'₹6,499',
        PriceDrop:'-46%',
        GetitBy:'Tommorrow,29October',
    }
    , {
        id:'5',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/81guvfQzeVL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Redmi 12C ",
        details:'Redmi 12C (Matte Black, 4GB RAM, 64GB Storage)',
        rating:'★ ★ ★ ★ ★',
        price:'₹6,999',
        PriceDrop:'-50%',
        GetitBy:'Tommorrow,29October',
    }  , {
        id:'6',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/71pKVhll1IL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Oneplus Open 5G",
        details:'Oneplus Open 5G (Emerald Dusk 16GB RAM, 512GB Storage)',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,39,999',
        PriceDrop:'-7%',
        GetitBy:'Tommorrow,29October',
    }  , {
        id:'7',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/71Zx7KyBrTL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Nokia G42 5G ",
        details:'Nokia G42 5G | Snapdragon® 480+ 5G ',
        rating:'★ ★ ★ ★ ★',
        price:'₹11,999',
        PriceDrop:'-25%',
        GetitBy:'Tommorrow,29October',
    } 
    , {
        id:'8',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/717X8H7re3L._AC_UY327_FMwebp_QL65_.jpg',
        heading:"itel P55 5G ",
        details:'itel P55 5G | Dimensity 6080 ',
        rating:'★ ★ ★ ★ ★',
        price:'₹9,999',
        PriceDrop:'-26%',
        GetitBy:'Tommorrow,29October',
    }   , {
        id:'9',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/813sVzTfvaL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Samsung Galaxy M04",
        details:'Samsung Galaxy M04 Light Green',
        rating:'★ ★ ★ ★ ★',
        price:'₹6,499',
        PriceDrop:'43%',
        GetitBy:'Tommorrow,29October',
    }   , {
        id:'10',
        category:'Mobile',
        subCategory:'Android',
        image:'https://m.media-amazon.com/images/I/61LB+d0vheL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"OnePlus Nord",
        details:'OnePlus Nord CE 3 Lite 5G ',
        rating:'★ ★ ★ ★ ★',
        price:'₹19,999',
        PriceDrop:'20%',
        GetitBy:'Tommorrow,29October',
    }   , {
        id:'11',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 13 ",
        details:'Apple iPhone 13 (128GB) - Midnight',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,499',
        PriceDrop:'-16%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'12',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 15",
        details:'Apple iPhone 15 (128 GB) - Blue',
        rating:'★ ★ ★ ★ ★',
        price:'₹79,900',
        PriceDrop:'3%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'13',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 13",
        details:'Apple iPhone 13 (128GB) - Pink',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,499',
        PriceDrop:'-16%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'14',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/81qlME2wWmL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 15 Pro",
        details:'Apple iPhone 15 Pro (1 TB) - White Titanium',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,84,900',
        PriceDrop:'-2%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'15',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 15",
        details:'Apple iPhone 15 (128 GB) - Blue',
        rating:'★ ★ ★ ★ ★',
        price:'₹79,900',
        PriceDrop:'-2%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'16',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/81Os1SDWpcL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 15 Pro Max",
        details:'Apple iPhone 15 Pro Max (256 GB) - Black Titanium',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,59,900',
        PriceDrop:'-0%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'17',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/71gm8v4uPBL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 13 ",
        details:'Apple iPhone 13 (128GB) - (Product) RED',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,499',
        PriceDrop:'-28%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'18',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 13 ",
        details:'Apple iPhone 13 (128GB) - Blue',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,499',
        PriceDrop:'-16%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'19',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/61nzPMNY8zL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 14 Pro Max",
        details:'Apple iPhone 14 Pro Max (1 TB) - Silver',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,89,900',
        PriceDrop:'-0%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'20',
        category:'Mobile',
        subCategory:'IPhone',
        image:'https://m.media-amazon.com/images/I/71T5NVOgbpL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple iPhone 14 Pro Max",
        details:'Apple iPhone 14 Pro Max (1 TB) - Gold',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,89,900',
        PriceDrop:'-0%',
        GetitBy:'Tomorrow, 29 October',
    }   , {
        id:'21',
        category:'Laptop',
        subcategory:'Laptop',
        image:'https://m.media-amazon.com/images/I/617rprfdhRL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Acer Aspire Lite ",
        details:'Acer Aspire Lite 12th Gen Intel Core i3-1215U Premium Metal Laptop',
        rating:'★ ★ ★ ★ ★',
        price:'₹31,990',
        PriceDrop:'-40%',
        GetitBy:'Thursday,16',
    }   , {
        id:'22',
        category:'Laptop',
        subcategory:'Laptop',
        image:'https://m.media-amazon.com/images/I/71I5fx8iPJL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Dell 15 Laptop,",
        details:'Dell 15 Laptop, Intel Core i5-1135G7 Processor/16GB DDR4/512GB SSD/Intel UHD Graphic/15.6" (39.562cm)',
        rating:'★ ★ ★ ★ ★',
        price:'₹48,990',
        PriceDrop:'-26%',
        GetitBy:'Thursday,16',
    }   , {
        id:'23',
        subcategory:'Laptop',
        category:'Laptop',
        image:'https://m.media-amazon.com/images/I/71fSS6dVWzL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP Laptop 15s",
        details:'HP Laptop 15s, 11th Gen Intel Core i3-1115G4, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD',
        rating:'★ ★ ★ ★ ★',
        price:'₹35,990',
        PriceDrop:'-20%',
        GetitBy:'Thursday,16',
    }   , {
        id:'24',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/31uLEZHhMDL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Lenovo V15 Intel",
        details:'Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm) FHD (1920x1080) Antiglare 250 Nits Thin and Light Laptop',
        rating:'★ ★ ★ ★ ★',
        price:'₹23,990',
        PriceDrop:'-43%',
        GetitBy:'Thursday,16',
    }   , {
        id:'25',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71vFKBpKakL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple MacBook Air",
        details:'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, 8GB RAM, 256GB SSD Storage, Backlit',
        rating:'★ ★ ★ ★ ★',
        price:'₹69,990',
        PriceDrop:'-30%',
        GetitBy:'Thursday,16',
    }   , {
        id:'26',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/41-Z3UHKoQL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP Laptop 15s",
        details:'HP Laptop 15s, 12th Gen Intel Core i3-1215U, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD',
        rating:'★ ★ ★ ★ ★',
        price:'₹38,205',
        PriceDrop:'-32%',
        GetitBy:'Thursday,16',
    }   , {
        id:'27',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71V2Q8g87XL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP 255 G9 ",
        details:'HP 255 G9 (840T7PA) Notebook (AMD Athlon Silver-3050U/ 4GB RAM/ 256GB SSD/DOS/ 15.6" Screen/ 1 Ye',
        rating:'★ ★ ★ ★ ★',
        price:'₹20,000 ',
        PriceDrop:'-26%',
        GetitBy:'Thursday,16',
    }   , {
        id:'28',
        category:'Laptop',
        subcategory:'Laptop',
        
        image:'https://m.media-amazon.com/images/I/71yjoXu2ZAL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP [SmartChoice] 15s",
        details:'HP [SmartChoice] 15s, Ryzen 5-5500U, 16GB RAM/512GB SSD 15.6"(39.6 cm) FHD Laptop/Alexa Built-in/Windows',
        rating:'★ ★ ★ ★ ★',
        price:'₹41,990',
        PriceDrop:'-29%',
        GetitBy:'Thursday,14',
    }   , {
        id:'29',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71WDKRWNdaL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP Laptop 15s",
        details:'HP Laptop 15s, AMD Ryzen 7 5700U, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, AMD Radeon Graphics,',
        rating:'★ ★ ★ ★ ★',
        price:'₹48,990 ',
        PriceDrop:'-24%',
        GetitBy:'Thursday,14',
    }   , {
        id:'30',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/619nJDbUDkL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"HP Chromebook X360",
        details:'HP Chromebook X360,Intel Celeron N4120,14-Inch (35.6 Cm),Hd,4Gb Lpddr4,64Gb Emmc,Intel Uhd',
        rating:'★ ★ ★ ★ ★',
        price:'₹22,990',
        PriceDrop:'-29%',
        GetitBy:'Thursday,16',
    }   , {
        id:'31',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71LVd5vKMfL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Acer [SmartChoice] One 14",
        details:'Acer [SmartChoice] One 14 Business Laptop AMD Ryzen 3 3250U Processor (8GB RAM/256GB SSD/AMD Radeon',
        rating:'★ ★ ★ ★ ★',
        price:'₹23,990',
        PriceDrop:'-38%',
        GetitBy:'Thursday,16',
    }   , {
        id:'32',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71-l4YfD2yL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"ASUS Vivobook",
        details:'ASUS Vivobook S 15 2022, Intel Core EVO i5-12500H 12th Gen, 15.6-inch (39.62 cms) FHD, Thin & Light Lapto',
        rating:'★ ★ ★ ★ ★',
        price:'₹56,990 ',
        PriceDrop:'-30%',
        GetitBy:'Thursday,16',
    }   , {
        id:'33',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71eQy-sS8GL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"ASUS Vivobook S 15",
        details:'ASUS Vivobook S 15 OLED (2023), Intel Core EVO i9-13900H 13th Gen, 15.6" (39.62 cm) 2.8K 120Hz OLED,',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,04,990',
        PriceDrop:'-22%',
        GetitBy:'Thursday,16',
    }   , {
        id:'34',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/61YCWzjldDL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"2023 MacBook Pro",
        details:'2023 MacBook Pro (14-inch, M3 chip with 8‑core CPU and 10‑core GPU, 8GB Unified Memory, 1TB) - Space Grey',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,89,900',
        PriceDrop:'0%',
        GetitBy:'Thursday,19',
    }   , {
        id:'35',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/61wn4H83q0L._AC_UY327_FMwebp_QL65_.jpg',
        heading:"ROG Zephyrus Duo 16",
        details:'ROG Zephyrus Duo 16, 16" (40.64 cm) UHD+/FHD+ 16:10 120Hz/240Hz/3ms, AMD Ryzen 9 6900HX, 16GB RTX',
        rating:'★ ★ ★ ★ ★',
        Price:'₹3,95,450',
        PriceDrop:'0%',
        GetitBy:'Thursday,16',
    }   , {
        id:'36',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/41s3VlAiN0L._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Qualcomm Mac OS 9",
        details:'Qualcomm Mac OS 9 Laptop 360 Model PR3 4GB',
        rating:'★ ★ ★ ★ ★',
        price:'₹24,499',
        PriceDrop:'-2%',
        GetitBy:'Thursday,16',
    }   , {
        id:'37',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/71vW1oV0iZL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Gen Intel Core i3",
        details:'Laptop 14s, 12th Gen Intel Core i3-1215U, 14-inch (35.6 cm), FHD, 8GB DDR4, 512GB SSD, Intel UHD Graphics,',
        rating:'★ ★ ★ ★ ★',
        price:'₹38,990',
        PriceDrop:'-24%',
        GetitBy:'Thursday,16',
    }   , {
        id:'38',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/61yag8HVkfL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"(Refurbished) Dell Latitude Air",
        details:'(Refurbished) Dell Latitude Air Laptop E7280 Intel Core i5 - 6300u Processor 6th Gen, 8 GB Ram & 512 GB SSD, 12',
        rating:'★ ★ ★ ★ ★',
        price:'₹23,990',
        PriceDrop:'-65%',
        GetitBy:'Thursday,16',
    }   , {
        id:'39',
        category:'Laptop',
        subcategory:'Laptop',

        image:'https://m.media-amazon.com/images/I/717hLEbS0CL._AC_UY327_FMwebp_QL65_.jpg',
        heading:" 11th Gen Intel Core i3",
        details:'[Smartchoice 14s, 11th Gen Intel Core i3-1125G4, 8GB RAM/256GB SSD 14"(35.6 cm) Micro-Edge, Anti-Glare,',
        rating:'★ ★ ★ ★ ★',
        price:'₹32,990',
        PriceDrop:'-30%',
        GetitBy:'Thursday,16',
    }   , {
        id:'40',
        category:'Laptop',
        subcategory:'Laptop',
        image:'https://m.media-amazon.com/images/I/71nQ0u851yL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Newly Launched NBC 3S ",
        details:'Newly Launched NBC 3S Core i3 12th Gen 1215U - (8 GB RAM 3200MHz/ 512 GB M.2 SATA SSD/Windows 11',
        rating:'★ ★ ★ ★ ★',
        price:'₹31,990',
        PriceDrop:'-37%',
        GetitBy:'Thursday,16',
    }   , {
        id:'41',
        category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/71VbHaAqbML._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 iPad Air",
        details:'Apple 2022 iPad Air M1 Chip (10.9-inch/27.69 cm, Wi-Fi, 64GB) - Blue (5th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,999 ',
        PriceDrop:'-15%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'42',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61goypdjAYL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 10.9-inch iPad",
        details:'Apple 2022 10.9-inch iPad (Wi-Fi, 64GB) - Silver (10th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹39,900',
        PriceDrop:'-11%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'43',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61XZQXFQeVL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 iPad",
        details:'Apple 2022 iPad Air M1 Chip (10.9-inch/27.69 cm, Wi-Fi, 64GB) - Space Gray (5th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,999 ',
        PriceDrop:'-15%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'44',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61lv79X8rsL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 10.9-inch ",
        details:'Apple 2022 10.9-inch iPad (Wi-Fi, 64GB) - Pink (10th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹39,900',
        PriceDrop:'-11%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'45',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/81WWJj1RedL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 11-inch",
        details:'Apple 2022 11-inch iPad Pro (Wi-Fi + Cellular, 128GB) - Space Grey (4th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹89,990',
        PriceDrop:'-7%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'46',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/71LRY1j6UHL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Xiaomi Pad 6",
        details:'Xiaomi Pad 6| Qualcomm Snapdragon 870| 144Hz Refresh Rate| 8GB, 256GB| 2.8K+ Display (11-inch/27.81cm)|1',
        rating:'★ ★ ★ ★ ★',
        price:'₹26,999',
        PriceDrop:'36%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'47',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61k05QwLuML._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 iPad Air",
        details:'Apple 2022 iPad Air M1 Chip (10.9-inch/27.69 cm, Wi-Fi, 256GB) - Purple (5th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹69,999',
        PriceDrop:'-7%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'48',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61uA2UVnYWL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 10.9-inch",
        details:'Apple 2022 10.9-inch iPad (Wi-Fi, 64GB) - Blue (10th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹39,900',
        PriceDrop:'-11%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'49',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/61oo+mrbI2L._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 10.9-inch",
        details:'Apple 2022 10.9-inch iPad (Wi-Fi, 64GB) - Yellow (10th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹44,900 ',
        PriceDrop:'0%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'50',
         category:'Tablets',
        subCategory:'IPads',
        image:'https://m.media-amazon.com/images/I/51KOc8HTlJL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Apple 2022 10.9-inch",
        details:'Apple 2022 10.9-inch iPad (Wi-Fi, 256GB) - Blue (10th Generation)',
        rating:'★ ★ ★ ★ ★',
        price:'₹29,999 ',
        PriceDrop:'15%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'51',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/71HXzfSx3eL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Samsung Galaxy Tab",
        details:'Samsung Galaxy Tab S9 27.81 cm (11 inch) Dynamic AMOLED 2X Display, RAM 12 GB, ROM 256 GB',
        rating:'★ ★ ★ ★ ★',
        price:'₹83,999',
        PriceDrop:'-11%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'52',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/61-9EA9rdiL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Samsung Galaxy Tab",
        details:'Samsung Galaxy Tab S9 FE 27.69 cm (10.9 inch) Display, RAM 8 GB, ROM 256 GB Expandable, S Pen in-Box, Wi-Fi',
        rating:'★ ★ ★ ★ ★',
        price:'₹47,999 ',
        PriceDrop:'-8%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'53',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/915rA4VNXuL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab S7 FE ",
        details:'Galaxy Tab S7 FE 31.5 cm (12.4 inch) Large Display, S-Pen in Box, Slim Metal Body, Dolby Atmos Sound, RAM 4 GB,',
        rating:'★ ★ ★ ★ ★',
        price:'₹32,999',
        PriceDrop:'-34%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'54',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/61vsK7h3zVL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab S6 Lite",
        details:'Galaxy Tab S6 Lite 26.31 cm (10.4 inch), S-Pen in Box, Slim and Light, Dolby Atmos Sound, 4 GB RAM, 64 GB ROM,',
        rating:'★ ★ ★ ★ ★',
        price:'₹32,999',
        PriceDrop:'-23%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'55',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/81GGUkR8MAL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab S8 ",
        details:'Galaxy Tab S8 | 27.81cm (11.0") LCD Display | 4nm Processor | 8,000 mAh Battery | Dolby Atmos Quad',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,999',
        PriceDrop:'-24%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'56',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/81Vs371KLML._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab S8",
        details:'Galaxy Tab S8 | 27.81cm (11.0") LCD Display | 4nm Processor | 8,000 mAh Battery | Dolby Atmos Quad',
        rating:'★ ★ ★ ★ ★',
        price:'₹50,999 ',
        PriceDrop:'-24%',
        GetitBy:'Thursday, 16',
    } , {
        id:'57',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/91SpB-8UCuS._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab A7 Lite",
        details:'Galaxy Tab A7 Lite 8.7 inches with Calling, Slim Metal Body, Dolby Atmos Sound, RAM 3 GB, ROM 32 GB',
        rating:'★ ★ ★ ★ ★',
        price:'₹12,390',
        PriceDrop:'-29%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'58',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/61M4gkurLUL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab S9 FE",
        details:'Galaxy Tab S9 FE 27.69 cm (10.9 inch) Display, RAM 6 GB, ROM 128 GB Expandable, S Pen in-Box, Wi-Fi, IP68 Table',
        rating:'★ ★ ★ ★ ★',
        price:'₹36,999',
        PriceDrop:'-18%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'59',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/61QnhDo0FEL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab A7 Lite",
        details:'Galaxy Tab A7 Lite 8.7" 32GB Android Tablet w/ Compact, Slim Design, Sturdy Metal Frame, Long Lasting Battery',
        rating:'★ ★ ★ ★ ★',
        price:'₹37,499',
        PriceDrop:'-6%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'60',
         category:'Tablets',
        subCategory:'SamsungPads',
        image:'https://m.media-amazon.com/images/I/91veRYPjpeL._AC_UY327_FMwebp_QL65_.jpg',
        heading:"Galaxy Tab A8 10.5 ",
        details:'Galaxy Tab A8 10.5 inches Display with Calling, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi+LTE Tablets, Gray, (SM-',
        rating:'★ ★ ★ ★ ★',
        price:'₹17,680',
        PriceDrop:'-39%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'61',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/41inm6XzSlL._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"Wood Set Top Box Stand",
        details:'Dime Store Engineered Wood Set Top Box Stand TV Stand WiFi Router Rack Wall Shelf for Living Room Stylish Hanging Rack Organizer Home Decor Furniture (Black)',
        rating:'★ ★ ★ ★ ★',
        price:'₹475',
        PriceDrop:'-32% ',
        GetitBy:'Thursday, 16',
    }  , {
        id:'62',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/81Vg6rYbFbL._AC_UL480_QL65_.jpg',
        heading:"Engineered Wood Wardrobe with Drawer",
        details:'Amazon Brand - Solimo Alpha 4 Door Engineered Wood Wardrobe with Drawer (Imperial Teak Finish)',
        rating:'★ ★ ★ ★ ★',
        price:'₹19,999 ',
        PriceDrop:'-40%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'63',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/61QIG7yCfEL._SX425_.jpg',
        heading:"Sheesham Wood 6 Seater Dining Table",
        details:'JODHPUR CITY FURNITURE Sheesham Wood 6 Seater Dining Table with Cushioned Chairs for Living Room Dining Room Furniture Set for Home (Honey Finish)',
        rating:'★ ★ ★ ★ ★',
        price:'₹23,499',
        PriceDrop:'-54%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'64',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/81fTd0YGauL._AC_UL480_QL65_.jpg',
        heading:" Wood Dining Table 4 Seater",
        details:'SONA ART & CRAFTS Modern Furniture Solid Sheesham Wood Dining Table 4 Seater Dining Table Set with 4 Cushion Chairs Dinner Table Set for Dinning',
        rating:'★ ★ ★ ★ ★',
        price:' ₹16,899',
        PriceDrop:'-52%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'65',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/91BX6yYvu0L._SX425_.jpg',
        heading:"3 Seater Sofa, Chenille Molfino Fabric",
        details:'Seventh Heaven Milan 3 Seater Sofa, Chenille Molfino Fabric: 3 Year Warranty (Maroon, 3 Seater)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹12,999',
        PriceDrop:'-24%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'66',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/513tBVV58ZL._AC_SR320,320_.jpg',
        heading:"Fabric 3 Seater Sofa",
        details:'Stone & Beam Lambertville Fabric 3 Seater Sofa (Grey)',
        rating:'★ ★ ★ ★ ★',
        price:'₹21,599',
        PriceDrop:'-62%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'67',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/91nx5fim1DL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"3 Seater Sofa",
        details:'Amazon Brand - Solimo Selsey 3 Seater Sofa (Fabric, Sand Brown)',
        rating:'★ ★ ★ ★ ★',
        price:'₹12,999',
        PriceDrop:'-73%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'68',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/71DjPd-Ln6L._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Single Seater Recliner",
        details:'duroflex Avalon Fabric Single Seater Recliner (Grey, DIY)',
        rating:'★ ★ ★ ★ ★',
        price:'₹14,953',
        PriceDrop:'-50%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'69',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/81bYaZ25MlL._SX425_.jpg',
        heading:"Computer Laptop Table",
        details:'BLUEWUD Walden Engineered Wood Study and Computer Laptop Table for Home or Office, WFH Desk, with Drawer Shelves Storage for Books and Décor Display for Adults Kids Students (Brown Maple & White)',
        rating:'★ ★ ★ ★ ★',
        price:'₹7,499',
        PriceDrop:'-48%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'70',
         category:'Home&Kitchen',
        subCategory:'Furniture',
        image:'https://m.media-amazon.com/images/I/612ElkFLzLL._AC_UL480_QL65_.jpg',
        heading:"Engineered Wood Study Table",
        details:'Green Soul Venue Engineered Wood Study Table (Rolex Brown) | Computer Desk, Office Table for Students, Adults, Professionals | 1 Drawer, 1 Shelf & 1 Cabinet | Warranty Protected',
        rating:'★ ★ ★ ★ ★',
        price:'₹5,998',
        PriceDrop:'-53%',
        GetitBy:'Thursday, 16',
    }  , {
        id:'71',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/81PM7pksrUL._SX425_.jpg',
        heading:"Buddha Monk Set Statue ",
        details:'Collectible India Buddha Monk Set Statue Home Decor Items Figurines Showpiece - Cute Mini Buddha Statue for Car Dashboard Table Top Diwali Home Decoration Gift Items (Type 1 Monk),Resin',
        rating:'★ ★ ★ ★ ★',
        price:' ₹199',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'72',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/41bux4M1HwL._SX300_SY300_QL70_FMwebp_.jpg',
        heading:" Brass Showpiece",
        details:'eCraftIndia Antique Music Decorative Canon Brass Showpiece (10 cm x 10 cm x 23.75 cm, Red and Brown)',
        rating:'★ ★ ★ ★ ★',
        price:'₹269',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'73',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/51CA0MIl-8L._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"Incense Holder Decorative",
        details:'HC VILLA Handicrafts Villa Ceramic Smoke Backflow Incense Holder Decorative Showpiece With 10 Scented Cone Incenses (Blue) (Conical)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹194',
        PriceDrop:'-73%',
        GetitBy:'Thursday, 16',
    } , {
        id:'74',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/910RSCX5U1L._SX425_.jpg',
        heading:"Good Luck Home Decor Item",
        details:'PREK Seven Chakra Crystals and Gemstones, Seven Chakra Crystal Tree Showpiece for Good Luck Home Decor Item Bonsai Money Tree Plant Gift Item Figurine Standard Size - Multicolor, 1 Piece',
        rating:'★ ★ ★ ★ ★',
        price:'₹599',
        PriceDrop:'-40%',
        GetitBy:'Thursday, 16',
    } , {
        id:'75',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/91XCBSv93oL._SX425_.jpg',
        heading:"Home Carpet Multi Colour",
        details:'LIZARUGS Hand Tufted Modern Latest Tiles Design Home Carpet Multi Colour (2X8 FEET)',
        rating:'★ ★ ★ ★ ★',
        price:'₹3,390',
        PriceDrop:'-35%',
        GetitBy:'Thursday, 16',
    } , {
        id:'76',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/51eggbhJeNL._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"Vintage Clock ",
        details:'Vintage Clock Iron Hand-Crafted Large Brass Colour Wall Clock (60 x 60 cm)',
        rating:'★ ★ ★ ★ ★',
        price:'₹2,599',
        PriceDrop:'-75%',
        GetitBy:'Thursday, 16',
    } , {
        id:'77',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/415qnAmtg7L._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"Wooden Wall Hanger",
        details:'Artvibes Padharo Sa Wooden Wall Hanger | Gifts | Bedroom | Decoration Items for Home | Mdf Wall Decoration for Living Room | Artworks Wall Hangings | Modern Decor Items (WH_7601N)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹229',
        PriceDrop:'-77%',
        GetitBy:'Thursday, 16',
    } , {
        id:'78',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/411D3QwSZvL._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"White Vase/Flower Vase/Pampas",
        details:'INDULGE HOMES - White Vase/Flower Vase/Pampas Grass Vase/Ceramic Vase/Round Shaped Vase/Home Decor Centrepiece/Decor Showpiece Donut Vase 6 & 8 Inches (Pack of 2)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹759',
        PriceDrop:'-62%',
        GetitBy:'Thursday, 16',
    } , {
        id:'79',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/41phCICGnUL._SX300_SY300_QL70_FMwebp_.jpg',
        heading:"Ceramic Figures",
        details:'Xtore Lucky Swan Couple Piano Finish Ceramic Figures for Home Decor (Set of 2 Pc, Large, White & Red)',
        rating:'★ ★ ★ ★ ★',
        price:'₹808',
        PriceDrop:'-80%',
        GetitBy:'Thursday, 16',
    } , {
        id:'80',
         category:'Home&Kitchen',
        subCategory:'HomeDecor',
        image:'https://m.media-amazon.com/images/I/813WLF9+5DL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Cushion Pillow Cover ",
        details:'KAAHIRA Handmade Cotton Macrame Cushion Pillow Cover Boho Home Decor Abstract Pattern 16 x 16 Inch in Off White Color - 1 Pcs',
        rating:'★ ★ ★ ★ ★',
        price:'₹331',
        PriceDrop:'-77%',
        GetitBy:'Thursday, 16',
    } , {
        id:'81',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/51Nin9ZvM7L._SY300_SX300_QL70_FMwebp_.jpg',
        heading:" Glass Serving Bowl",
        details:'PINNAZ INTERNATIONAL Glass Serving Bowl with Lid Oven Microwave Safe Casserole | Vessel for Curry Kitchen Server Ware| Mixing Pottery for Snacks Cake Cereal Rice Sambar | (Transparent) (1600ML)',
        rating:'★ ★ ★ ★ ★',
        price:'₹1,225',
        PriceDrop:'-53%',
        GetitBy:'Thursday, 16',
    }, {
        id:'82',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/41RozqkS3BL._SY300_SX300_QL70_FMwebp_.jpg',
        heading:"Non-Stick Black Cookware Set",
        details:'amazon basics Aluminium Non-Stick Black Cookware Set - 15 Piece',
        rating:'★ ★ ★ ★ ★',
        price:' ₹3,499',
        PriceDrop:'-60%',
        GetitBy:'Thursday, 16',
    } , {
        id:'83',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/517nDmj1i8L._AC_UL480_FMwebp_QL65_.jpg',
        heading:" Mio Nonstick Aluminium Cookware Gift Set",
        details:'Pigeon by Stovekraft Mio Nonstick Aluminium Cookware Gift Set, Includes Nonstick Flat Tawa, Nonstick Fry Pan, Kitchen Tool Set, Kadai with Glass Lid, 8 Pieces Non-Induction Base Kitchen Set - Red',
        rating:'★ ★ ★ ★ ★',
        price:'₹999',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'84',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/710Y9jdtjFL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Stainless Steel Lunch Box",
        details:'Attro Lunchmate Stainless Steel Airtight Leak-Proof Lunch Box for Office, School, Picnic, 800 ml - Green',
        rating:'★ ★ ★ ★ ★',
        price:'₹429',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'85',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/71cFxsy+BCL._SX425_.jpg',
        heading:" Electric Kettle",
        details:'Butterfly EKN 1.5-Litre Electric Kettle (Silver with Black)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹549',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'86',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/71ZmmLW97YL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Airtight Canister Set",
        details:'Cello Checkers Pet Plastic Airtight Canister Set | Food grade and BPA free canisters | Durable & Shatterproof Body |Air tight seal & Stackable | Free from any kind of odor | Transparent | 300ml x 6, 650ml x 6, 1200 x 6, Set of 18',
        rating:'★ ★ ★ ★ ★',
        price:'₹449',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'87',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/71LML7H192L._AC_UL480_FMwebp_QL65_.jpg',
        heading:" Vegetable Chopper Cutter",
        details:'Ganesh Multipurpose Plastic Vegetable Chopper Cutter 3 Blades for Effortlessly Chopping Vegetables and Fruits for Your Kitchen, Pool Green (725 ml)',
        rating:'★ ★ ★ ★ ★',
        price:' ₹139',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'88',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://images-eu.ssl-images-amazon.com/images/I/41H8Ae-loUL._AC_SX184_.jpg',
        heading:"CAROTE Non Stick Cookware Set",
        details:'CAROTE Non Stick Cookware Set, Induction Set Combo, Set of 4(24cm Fry Pan, 16cm Saucepan, 24cm Sauce Pot, 28cm Biryani Pot, 16cm Lid, 24cm Lid, 28cm LidGreen)',
        rating:'★ ★ ★ ★ ★',
        price:'₹4,299',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'89',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://images-eu.ssl-images-amazon.com/images/I/41NOqIn14IL._AC_SX184_.jpg',
        heading:"Lagoon Dinner Set",
        details:'Cello Opalware Dazzle Series Tropical Lagoon Dinner Set, 18 Units | Opal Glass Dinner Set for 6 | Light-Weight, Daily Use Crockery Set for Dining | White Plate and Bowl Set',
        rating:'★ ★ ★ ★ ★',
        price:' ₹949',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'90',
         category:'Home&Kitchen',
        subCategory:'Kitchen&Dinning',
        image:'https://m.media-amazon.com/images/I/81mrMggUQnS._SX425_.jpg',
        heading:"Stainless Steel Water Bottle",
        details:'Amazon Brand - Solimo Slim Stainless Steel Water Bottle, Set of 3, 1 L Each',
        rating:'★ ★ ★ ★ ★',
        price:'₹529',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/3/6/36a8a978904320745868_1new.jpg',
        heading:"SUGAR Play Be Boujee Powder Blush",
        details:'SUGAR Play Be Boujee Powder Blush',
        rating:'★ ★ ★ ★ ★',
        price:'₹499',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/4/f/4f069ea0LOVEE00000005_1.jpg',
        heading:"Love Earth Multipot Lip and Cheek Tint",
        details:'Love Earth Multipot Lip and Cheek Tint',
        rating:'★ ★ ★ ★ ★',
        price:'₹229',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/6/5/655517fPIPAB00002165_1.jpg',
        heading:"Pipa Bella by Nykaa Fashion Badass Black",
        details:'Pipa Bella by Nykaa Fashion Badass Black',
        rating:'★ ★ ★ ★ ★',
        price:'₹697',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/4/7/4753524chiwm00116-c4__1_.jpg',
        heading:"Royal Son Butterfly Uv Protection Women Sunglasses Black Len",
        details:'Royal Son Butterfly Uv Protection Women Sunglasses Black Len',
        rating:'★ ★ ★ ★ ★',
        price:'₹664',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/6/1/611a6058904245710040_2.jpg',
        heading:"Nykaa Cosmetics Matte Luxe Lipstick",
        details:'Nykaa Cosmetics Matte Luxe Lipstick',
        rating:'★ ★ ★ ★ ★',
        price:'₹552',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/0/9/09f21423605972495716_1.jpg',
        heading:"Urban Decay Vice Lipstick",
        details:'Urban Decay Vice Lipstick',
        rating:'★ ★ ★ ★ ★',
        price:'₹2200',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'91',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/2/4/24289d841554433784_1.jpg',
        heading:"Maybelline New York Fit Me Matte + Poreless Powder",
        details:'Maybelline New York Fit Me Matte + Poreless Powder',
        rating:'★ ★ ★ ★ ★',
        price:'₹440',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'98',
         category:'Beauty',
        subCategory:'Makeup',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/a/8/a8fa5f5773602042951_1.jpg',
        heading:"M.A.C Studio Fix Powder Plus Foundation - NC42",
        details:'M.A.C Studio Fix Powder Plus Foundation - NC42',
        rating:'★ ★ ★ ★ ★',
        price:'₹3300',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/51A9eygJmrL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Fulgurant White Crystal Necklace For Women -",
        details:'Fulgurant White Crystal Necklace For Women -',
        rating:'★ ★ ★ ★ ★',
        price:'₹3,444',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/41eVDXH+N1L._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Elan Necklace Rose Gold Stainless Steel (316L) And Ros",
        details:'Elan Necklace Rose Gold Stainless Steel (316L) And Ros',
        rating:'★ ★ ★ ★ ★',
        price:'₹4,199',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/81esl6C2v1L._SY395_.jpg',
        heading:"Sukkhi Exotic Oxidised Pearl Chandelier Earring For Women (SKR56889)",
        details:'Sukkhi Exotic Oxidised Pearl Chandelier Earring For Women (SKR56889)',
        rating:'★ ★ ★ ★ ★',
        price:'₹510',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/71CSGmv8tQL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Latest Stylish Fancy Oxidised Silver Tribal Necklace Jeweller",
        details:'Latest Stylish Fancy Oxidised Silver Tribal Necklace Jeweller',
        rating:'★ ★ ★ ★ ★',
        price:'₹299',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/41mLnXcUVKL._AC_SR320,320_.jpg',
        heading:"Diamond Earrings for Women",
        details:'Priyaasi Geometric Design American Diamond Earrings for Women | Stylish Drop Look | Silver-Plated Earrings for Girls | Ethnic Wear | Gift for Women & Girls',
        rating:'★ ★ ★ ★ ★',
        price:' ₹389',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/510LmaI2uiL._AC_SR270,180_QL70_.jpg',
        heading:"Rhinestone Earrings",
        details:'CHERRY WONDERS Purple Square Crystal Rhinestone Earrings Elegant - Geometric Diamond Earrings Women',
        rating:'★ ★ ★ ★ ★',
        price:'₹299',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'99',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/71H5ua7RATL._AC_SR270,180_QL70_.jpg',
        heading:"RedDiamond DropEarrings",
        details:'DISHIS Womenand Garnet RedDiamond DropEarrings',
        rating:'★ ★ ★ ★ ★',
        price:'₹11,451',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'106',
         category:'Beauty',
        subCategory:'Jwellery',
        image:'https://m.media-amazon.com/images/I/71yNBNYlDML._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Diamond Silver Plated Alloy Necklace Set with Earrings For",
        details:'Diamond Silver Plated Alloy Necklace Set with Earrings For women',
        rating:'★ ★ ★ ★ ★',
        price:'₹245 ',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'107',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/61A0E5h8I9L._SY355_.jpg',
        heading:"Engage Verona Perfume ",
        details:'Engage Verona Perfume for Women, Long Lasting, Citrus and Fruity, for Everyday Use, Gift for Women, Free Tester with pack, 100ml',
        rating:'★ ★ ★ ★ ★',
        price:' ₹300',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'108',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/61TlWuB9G-L._AC_CR0%2C0%2C0%2C0_SX960_SY720_.jpg',
        heading:"Park Avenue Perfume For Men",
        details:'Park Avenue Perfume For Men, Euphoria, 100ml Eau De Parfum, Premium, Long Lasting, Intense Fragrance Spray, Suitable For Every Occasion',
        rating:'★ ★ ★ ★ ★',
        price:'₹374',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'109',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/613pg4Wtl-L._AC_CR0%2C0%2C0%2C0_SX960_SY720_.jpg',
        heading:"Park Avenue Harmony ",
        details:'Park Avenue Harmony – Eau De Parfum Men, 100ml | Perfume for Men | Premium Luxury Fragrance Scent | Long-lasting Aroma Perfume',
        rating:'★ ★ ★ ★ ★',
        price:'₹374',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'110',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/615ovi+7udL._SY355_.jpg',
        heading:"Hydra Energy Premium ",
        details:'Wild Stone Hydra Energy Premium Eau De Parfum for Men, 100ml|Long Lasting Perfume|Luxury Perfume for Men',
        rating:'★ ★ ★ ★ ★',
        price:' ₹287',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'111',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/61n-EtsZZYL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"NikeCasual Women Combo",
        details:'NikeCasual Women Combo',
        rating:'★ ★ ★ ★ ★',
        price:'₹629',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'112',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://m.media-amazon.com/images/I/61KP5-h5ANL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Perfume Combo Of TalkMe-Sandal-",
        details:'ST.FONTPerfume Combo Of TalkMe-Sandal- Pleasame (Pack of 3)',
        rating:'★ ★ ★ ★ ★',
        price:'₹249',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'113',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://images-static.nykaa.com/media/catalog/product/a/c/ac85482BELAB00000048d_1.jpg?tr=w-344,h-344,cm-pad_resize',
        heading:"Bella Vita Luxury Perfumes ",
        details:'Bella Vita Luxury PerfumesGift Set For Women(80ml)',
        rating:'★ ★ ★ ★ ★',
        price:'₹535',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    } , {
        id:'114',
         category:'Beauty',
        subCategory:'Perfumes',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/1/3/13592a28904245710668New1.jpg',
        heading:"Moi By Nykaa Eau de Perfume",
        details:'Moi By Nykaa Eau de Perfume',
        rating:'★ ★ ★ ★ ★',
        price:'₹1800',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }, {
        id:'115',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/71xSuLxL3yL._SY500_.jpg',
        heading:" Round Sling Crossbody Bag ",
        details:'DailyObjects Orbis Round Sling Crossbody Bag For Women| Beautiful Print Vegan Leather Purse With Slip Pocket Inside| Zip Closure & Adjustable Strap| Storage Space For Essentials',
        rating:'★ ★ ★ ★ ★',
        price:' ₹1,099',
        PriceDrop:'-50%',
        GetitBy:'Thursday, 16',
    }, {
        id:'116',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/41c-9IFNuDL._AC_SR320,320_.jpg',
        heading:"",
        details:"LAPIS O LUPO Women'sHandbag andSling Bag Combo (Black) (Set of 2)",
        rating:'★ ★ ★ ★ ★',
        price:'₹439',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'117',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/41lOd-eQg3L._AC_SR320,320_.jpg',
        heading:"Leather Handbags Shoulder Bag",
        details:'LAPIS O LUPO Women Fashion Synthetic Leather Handbags Shoulder Bag and Sing bag 2pcs Set',
        rating:'★ ★ ★ ★ ★',
        price:' ₹615',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'118',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/41vuCvcRl6L._AC_SR320,320_.jpg',
        heading:"Leather Women Handbags",
        details:'INOVERA Faux Leather Women Handbags Shoulder Hobo Bag Purse With Long Strap (Black) (Brown)',
        rating:'★ ★ ★ ★ ★',
        price:'',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'119',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/81+5Z7vYocL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"DANIEL CLARK Handbags For Women Combo",
        details:'DANIEL CLARK Handbags For Women Combo',
        rating:'★ ★ ★ ★ ★',
        price:' ₹489',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'120',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/714-q7zer2L._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Grace Solid Tote Bag for Women with Adjustable &",
        details:'Grace Solid Tote Bag for Women with Adjustable &',
        rating:'★ ★ ★ ★ ★',
        price:'₹2,484',
        PriceDrop:'-30%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'121',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://m.media-amazon.com/images/I/51b2Ii+fFcL._AC_UL480_FMwebp_QL65_.jpg',
        heading:"Amazon Brand - Eden & Ivy",
        details:'Brand: Amazon Brand - Eden & IvyAmazon Brand - Eden & Ivy WomenHandbag',
        rating:'★ ★ ★ ★ ★',
        price:' ₹669',
        PriceDrop:'-65%',
        GetitBy:'Thursday, 16',
    }   , {
        id:'122',
         category:'Beauty',
        subCategory:'Handbags',
        image:'https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/2/2/227a779MIRAG00000397_1.jpg',
        heading:"MIRAGGIO Kathy Hobo bag",
        details:'MIRAGGIO Kathy Hobo bag',
        rating:'★ ★ ★ ★ ★',
        price:'₹2324',
        PriceDrop:'34% Off',
        GetitBy:'Thursday, 16',
    }            
]
module.exports=data;